Controllers/SubscriptionController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Recurly;
using Svp.RecurlyApi.Test.Web.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;

namespace Svp.RecurlyApi.Test.Web.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly Client _client;
        private readonly ILogger<SubscriptionController> _logger;
        private readonly string _mysewnetApiUrl;
        public SubscriptionController(ILogger<SubscriptionController> logger, IConfiguration config)
        {
            _logger = logger;
            //recurly api key
            _client = new Client(config["RecurlyApiKey"]);
            _mysewnetApiUrl = config["MysewnetApiUrl"];
        }
        public IActionResult Index()
        {
            return View();
            //return RedirectToAction("BillingInfo");
        }
        public IActionResult Silver()
        {
            SubscriptionViewModel model = new()
            {
                PlanCode = "620151096",
                PlanDescription = "mysewnet_silver_subscription",
                Amount = 24.99M,
                CompanyCode = "SVPSEWINGBRANDSLLC",
                CurrencyCode = "USD",
                TaxCode = "DC020502",
                AddressLine2 = "",
                AccountId = "4120257",
                AddressLine1 = "141 W Jackson Blvd",
                City = "Chicago",
                Zip = "60604",
                State = "IL",
                Country = "US",
                Email = "sunila@tadigital.com"
            };
            return View(model);
        }
        public IActionResult Platinum()
        {
            SubscriptionViewModel model = new()
            {
                PlanCode = "620151296",
                PlanDescription = "mysewnet_platinum_subscription",
                Amount = 49.99M,
                CompanyCode = "SVPSEWINGBRANDSLLC",
                CurrencyCode = "USD",
                TaxCode = "DC020502",
                AddressLine2 = "",
                AccountId = "4120257",
                AddressLine1 = "141 W Jackson Blvd",
                City = "Chicago",
                Zip = "60604",
                State = "IL",
                Country = "US",
                Email = "sunila@tadigital.com"
            };
            return View(model);
        }
        public IActionResult AddCardDetails(SubscriptionViewModel model)
        {
            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    string url = $"{_mysewnetApiUrl}/Migration/CreateTransaction?taxCode={model.TaxCode}&itemCode={model.PlanCode}&description={model.PlanDescription}&amount={model.Amount}&address1={model.AddressLine1}&address2={model.AddressLine2}&city={model.City}&region={model.State}&postalCode={model.Zip}&country={model.Country}&companyCode={model.CompanyCode}&customerCode={model.AccountId}&currencyCode={model.CurrencyCode}&email={model.Email}";
                    var responseMessage = httpClient.GetAsync(new Uri(url)).Result;
                    var responseContent = responseMessage.Content.ReadAsStringAsync().Result;
                    if (!responseMessage.IsSuccessStatusCode)
                        throw new Exception("Failed to create order in Avalara");

                    return Ok(responseContent);
                }
            }
            catch (Exception e)
            {

            }

            return Ok();
            //return RedirectToAction("BillingInfo");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recurly Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://js.recurly.com/v4/recurly.css" rel="stylesheet" type="text/css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://js.recurly.com/v4/recurly.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recurly Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BillingInfo">Billing Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="Index">Choose Plan</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Recurly Test <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>